### ISSUE TITLE
Off by one error in echo example

### ISSUE THREAD

**Issue by ndkrempel** [kriskowal/gtor#32]
In the *echo() generator function example:

After .next(x), the value x is the next value yielded, so the expect calls are all off by one.

**Comment by bergus** [comment]
Good catch. I guess the example should be
```
function *echo() {
    var message,
        message2 = function.next; // the value of the first .next() call
    while (true) {
        message1 = yield message1;
        message2 = yield message2;
    }
}
```
or, if we wanted to get fancy and use a single yield only,
```
function *echo() {
    var messages = [ , function.next];
    while (true) {
        messages.push(yield messages.shift());
    }
}
```

**Comment by kriskowal** [comment]
The error is in fact a good catch. However, since the point of the example is to illustrate the behavior of the generator from a very basic implementation, the resolution is to fix the expected behavior and surrounding prose, hopefully without crippling the point. Thanks for pointing this out.

**Comment by Gahen** [comment]
Do you mind if I attempt a PR to fix this?

**Comment by kriskowal** [comment]
@Gahen You’re welcome to. See my prior note.

**Comment by Gahen** [comment]
@kriskowal Ok so I didn't wanted to change the code spirit because I would need to remove most of the following text, so I made a simpler fix and added an extra line just to complete the execution described. It would be like this:

```javascript
function *echo() {
    var message, tmp_message, old_message;
    while (true) {
        message = yield old_message;
        old_message = tmp_message;
        tmp_message = message; 
    }
}
```

We then populate the message variable with a value, receiving its former
undefined content again.
+ After that we take the previous yielded value and save it for the next iteration.
